name: Code Quality

on:
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Check Backend code formatting
        working-directory: backend
        run: npm run lint

      - name: Check Frontend code formatting
        working-directory: frontend
        run: npm run lint

      - name: TypeScript check - Backend
        working-directory: backend
        run: npx tsc --noEmit

      - name: TypeScript check - Frontend
        working-directory: frontend
        run: npx tsc --noEmit
